services:
  ENV-ibt-front:
    container_name: ENV-ibt-front
    image: registry.ibt.ru:5050/ibt-admin:${TAG}
    restart: always
    env_file:
      - /home/iBT.studio/ENV/svc/ibt-admin/.env
    environment:
      - PHP_SOCK_FILE=/sockets/ENV-ibt-admin_php
    volumes:
      - /sockets/:/sockets/
      - /home/iBT.studio/ENV/svc/ibt-admin/.env:/var/www/.env
    hostname: ibt-admin.ENV
    networks:
      ENV.svc.cluster.local:
        aliases:
          - ibt-admin.ENV.svc.cluster.local
    extra_hosts:
      - "mysql-master:host-gateway"
